# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

project_name: s3-proxy

before:
  hooks:
    - make code/clean
    - make setup/dep/install

builds:
  - main: ./cmd/s3-proxy
    binary: s3-proxy
    flags:
      - -trimpath
    ldflags:
      - -extldflags "-static"
      - -X github.com/oxyno-zeta/s3-proxy/pkg/s3-proxy/version.Version={{ .Tag }}
      - -X github.com/oxyno-zeta/s3-proxy/pkg/s3-proxy/version.GitCommit={{ .ShortCommit }}
      - -X github.com/oxyno-zeta/s3-proxy/pkg/s3-proxy/version.BuildDate={{ .Date }}
      # Clear the "unreleased" string in Metadata
      - -X github.com/oxyno-zeta/s3-proxy/pkg/s3-proxy/version.Metadata=
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "6"
      - "7"
    goos:
      - windows
      - darwin
      - linux
    ignore:
      - goos: darwin
        goarch: "386"

archives:
  - format: tar.gz
    files:
      - LICENSE
      - README.md
      - templates/*
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

release:
  github:
    owner: oxyno-zeta
    name: s3-proxy
  prerelease: auto

dockers:
  - goos: linux
    goarch: amd64
    ids:
      - s3-proxy
    image_templates:
      - "oxynozeta/s3-proxy:{{ .Version }}-amd64"
    skip_push: false
    use: buildx
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=oxyno-zeta.s3-proxy.version={{ .Version }}"
      - "--label=oxyno-zeta.s3-proxy.name={{ .ProjectName }}"
    extra_files:
      - templates/
  - goos: linux
    goarch: arm
    goarm: 6
    ids:
      - s3-proxy
    image_templates:
      - "oxynozeta/s3-proxy:{{ .Version }}-armv6"
    skip_push: false
    use: buildx
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/arm/v6"
      - "--label=oxyno-zeta.s3-proxy.version={{ .Version }}"
      - "--label=oxyno-zeta.s3-proxy.name={{ .ProjectName }}"
    extra_files:
      - templates/
  - goos: linux
    goarch: arm
    goarm: 7
    ids:
      - s3-proxy
    image_templates:
      - "oxynozeta/s3-proxy:{{ .Version }}-armv7"
    skip_push: false
    use: buildx
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/arm/v7"
      - "--label=oxyno-zeta.s3-proxy.version={{ .Version }}"
      - "--label=oxyno-zeta.s3-proxy.name={{ .ProjectName }}"
    extra_files:
      - templates/
  - goos: linux
    goarch: arm64
    ids:
      - s3-proxy
    image_templates:
      - "oxynozeta/s3-proxy:{{ .Version }}-arm64"
    skip_push: false
    use: buildx
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/arm64/v8"
      - "--label=oxyno-zeta.s3-proxy.version={{ .Version }}"
      - "--label=oxyno-zeta.s3-proxy.name={{ .ProjectName }}"
    extra_files:
      - templates/

docker_manifests:
  - name_template: oxynozeta/s3-proxy:latest
    image_templates:
      - "oxynozeta/s3-proxy:{{ .Version }}-amd64"
      - "oxynozeta/s3-proxy:{{ .Version }}-arm64"
      - "oxynozeta/s3-proxy:{{ .Version }}-armv6"
      - "oxynozeta/s3-proxy:{{ .Version }}-armv7"
  - name_template: "oxynozeta/s3-proxy:{{ .Version }}"
    image_templates:
      - "oxynozeta/s3-proxy:{{ .Version }}-amd64"
      - "oxynozeta/s3-proxy:{{ .Version }}-arm64"
      - "oxynozeta/s3-proxy:{{ .Version }}-armv6"
      - "oxynozeta/s3-proxy:{{ .Version }}-armv7"
  - name_template: "oxynozeta/s3-proxy:{{ .Major }}"
    image_templates:
      - "oxynozeta/s3-proxy:{{ .Version }}-amd64"
      - "oxynozeta/s3-proxy:{{ .Version }}-arm64"
      - "oxynozeta/s3-proxy:{{ .Version }}-armv6"
      - "oxynozeta/s3-proxy:{{ .Version }}-armv7"
  - name_template: "oxynozeta/s3-proxy:{{ .Major }}.{{ .Minor }}"
    image_templates:
      - "oxynozeta/s3-proxy:{{ .Version }}-amd64"
      - "oxynozeta/s3-proxy:{{ .Version }}-arm64"
      - "oxynozeta/s3-proxy:{{ .Version }}-armv6"
      - "oxynozeta/s3-proxy:{{ .Version }}-armv7"
