name: Deploy PROD

on:
  push:
    tags:
      - "v*"
env:
  IMAGE_NAME: hieunt87/s3-proxy

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.23"
        cache: false
    - name: Install modules
      run: go mod tidy
    - name: Build app
      run: go build -o ../s3-proxy ./cmd/s3-proxy/main.go
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.IMAGE_NAME }}
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Docker build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./management/Dockerfile
        platforms: linux/amd64
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        push: true